project:
  type: website
  preview:
    port: 7567
  render:
    - "./*.qmd"
  post-render:
    - cp -r ../data _site/data
  resources:
    - slides

website:
  title: "Next Generation Shiny Apps with {bslib}"
  description: "A tutorial on how to create modern Shiny apps with {bslib} and {shiny}"
  page-footer: |
    <a href="https://rconsortium.github.io/RMedicine_website/">R/Medicine 2024</a>
  navbar:
    title: "Next-Gen Shiny Apps"
    foreground: black
    background: white
    left:
      - href: index.qmd
        text: Home
      - href: workshop.qmd
        text: Workshop
      - about.qmd
  page-navigation: true
  sidebar:
    - id: workshop
      style: docked
      type: light
      background: light
      foreground: dark
      contents:
        - workshop.qmd
        - text: '<div class="sidebar-divider font-monospace">Hour 1</div>'
        - workshop-01.qmd
        - workshop-02.qmd
        - workshop-03-break.qmd
        - text: '<div class="sidebar-divider font-monospace">Hour 2</div>'
        - workshop-04.qmd
        - workshop-05.qmd
        - workshop-06.qmd
        - workshop-07-break.qmd
        - text: '<div class="sidebar-divider font-monospace">Hour 3</div>'
        - workshop-08.qmd
        - workshop-09.qmd
        - workshop-10.qmd
        - workshop-11.qmd

format:
  html:
    theme: [zephyr, styles.scss]
    css:
      - auto-dark-mode.css
    toc: true
    include-before-body:
      - text: <script>document.querySelector('.navbar').dataset.bsTheme = 'light';</script>

filters:
  - shinylive

editor:
  render-on-save: true