---
title: New layouts
description: |
  Learn how to lay out UI elements with bslib.
duration: 30min

editor: { render-on-save: true }
---

- (10) Introducing
    - `page_sidebar()`
    - `card()`
        - with card parts
    - `layout_columns()`
    - full screen cards

- (10) Breakout activity
    - Starting with a basic shiny app with 2 inputs and 2-3 plots
        - (1 input is more local)
    - Organize into a new layout
    - Bonus: `layout_sidebar()`

- (10) Value Boxes
    - Quick code intro
    - Short on-your-own
        - Use buid-a-box app to explore options
        - Create one target value box
        - Make your own for another

## 🧑‍💻 Your Turn {#your-turn-layout}

::: lead
<i class="bi bi-folder-symlink-fill"></i> `exercises/02_app.R`
:::

We're in the process of refactoring an older Shiny app to use new features from bslib.
I've started refactoring `exercises/02_app.R` by pulling out the inputs so it's easier to see the layout.

Your task is to migrate the UI section of the app from `shiny::fluidPage()` and `shiny::sidebarLayout()` to use page and layout functions from `{bslib}`.

## 🧑‍💻 Your Turn {#your-turn-value-box}

::: lead
<i class="bi bi-folder-symlink-fill"></i> `exercises/03_app.R`
:::

The app in `exercises/03_app.R` contains the start of a dashboard where the user can pick a specific school and see a quick summary of information about the school.

I've set up all of the reactive server-side logic for you.
Your job is to create three visually appealing value boxes to describe:

1. The number of undergraduate students at the school.
2. The average yearly cost of the school.
3. The rate of completion at the school.

::: {.callout-tip}
Use the Build-A-Box app from the bslib package to explore value box options and to design the three value boxes.
The [app is available online](https://bslib.shinyapps.io/build-a-box/) or locally by running

```r
shiny::runExample("build-a-box", package = "bslib")
```
:::
