---
title: Welcome and Getting Started
description: |
  Welcome to the workshop and hello, bslib!
duration: 25min

editor: { render-on-save: true }
---

{{< revealjs "slides/slides-01.html" >}}


- Welcome to R/Medicine 2024!
  - Who am I
  - Where to find things
  - How to ask questions
  - How we'll do this thing
    - A bit of teaching
    - with break-out pairing sessions

- What is bslib?
  - Started as a way to style your Shiny apps
  - And bringing Bootstrap 5 to Shiny
  - Now a whole lot more

- Breakout activity: Are we all set up?
  - Take a Shiny app and make it bslib-ier
    - From `{type}Page()` to `page_{type}()`
    - Try out Bootsrap/Bootswatch themes
    - Extra points: try a Sass variable
  - Help each other make sure you're set up

- Follow up
  - Check in
  - Introduce the College Scorecard dataset
  - Bonus: [new `shinyapp` snippet](https://www.garrickadenbuie.com/blog/shiny-new-bslib-snippet/)


## 🧑‍💻 Your Turn {#your-turn}

::: lead
<i class="bi bi-folder-symlink-fill"></i> `exercises/01_app.R`
:::

**Are we all set up?**
Open the app in `exercises/01_app.R`.
Run the app to make sure it works.
Can everyone in your breakout session run the app?
Help each other make sure you're set up.

**Take a Shiny app and make it bslib-ier**
Replace `fluidPage()` with `page_fluid()`.
What other page types are available?
Try out some [Bootswatch themes](https://bootswatch.com).
For bonus points, try setting [a theme-related Sass variable](https://rstudio.github.io/bslib/articles/bs5-variables/index.html).

**Use the app to learn about the variables in `school`.**